### ISSUE TITLE
Input system

### ISSUE THREAD

**Issue by duc0905** [duc0905/BoredGameEngine#1]
- Create Input system that is able to register callback to handle inputs.
- Able define contexts which define set of actions that are available if activated.
- User are able to define what actions are in a context and what contexts are being used

- [x] Keyboard input
- [x] Mouse input

**Comment by kipiiler** [comment]
.... issue j to vl

**Comment by kipiiler** [comment]
break downnnnn

**Comment by kipiiler** [comment]
cai nay xong chua

**Comment by duc0905** [comment]
Còn mấy loại input nữa, cơ mà

**Comment by kipiiler** [comment]
chuot lam nnao co

**Comment by duc0905** [comment]
ko biết
