### ISSUE TITLE
Setup Test project

### ISSUE THREAD

**Issue by duc0905** [duc0905/BoredGameEngine#2]
Setup a project that includes modules from the main engine and run tests on them.

**Comment by kipiiler** [comment]
Test proj khac test syten na

**Comment by duc0905** [comment]
Test thì nên để riêng ra vì code ko thôi đã phức tạp rồi lại còn nhét thêm đống test code vào nữa thì ko ổn

Test proj này sẽ chứa cái framework test của mình, 1 project nữa dùng để viết unit test cho engine. Client muốn test thì tạo proj mới xong dùng framework của mình
