### ISSUE TITLE
Update OpenGLRenderer

### ISSUE THREAD

**Issue by duc0905** [duc0905/BoredGameEngine#28]
- Now: OpenGLRenderer renders the texture of the mesh using the UV of the vertices.
Goal: The renderer should use the textures to render the mesh

Basic guideline:
- Read the Texture class created in #27 
- Rewrite the shaders to take texture data to render
- Rewrite the Render(Mesh&) method of the renderer:
- Get texture data and bind it to the shader before render the mesh

Useful links
- [Shader basic](https://ogldev.org/www/tutorial04/tutorial04.html)
- [Basic texture](https://ogldev.org/www/tutorial16/tutorial16.html)
- [Assimp usage](https://ogldev.org/www/tutorial22/tutorial22.html)

**Comment by kipiiler** [comment]
@duc0905 cai nay hnhu xong r
